spring:
  mvc:
    format:
      date: iso
  datasource:
    url: jdbc:postgresql://localhost:5432/web-store
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true
        hbm2ddl:
        auto: validate
        current_session_context_class: thread
        cache:
          use_second_level_cache: true
          use_query_cache: true
          cache:
            region:
              factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 102879123337-ddre6f1ummvqi11b380d6dutmktt1b7b.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8090/login/oauth2/code/google

logging:
  level:
    root: INFO
server:
  port: 8090
